import { defineArrayMember, defineField, defineType } from "sanity";

export const courseType = defineType({
  name: "course",
  title: "Course",
  type: "document",
  groups: [
    { name: "listing", title: "Listing" },
    { name: "hero", title: "Hero" },
    { name: "details", title: "Details" },
    { name: "cta", title: "CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "listing",
      validation: (rule) => rule.required().min(6).max(120),
    }),
    defineField({
      name: "shortTitle",
      title: "Short Title",
      type: "string",
      group: "listing",
      validation: (rule) => rule.required().min(4).max(80),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "listing",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tag",
      title: "Tag",
      type: "string",
      group: "listing",
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
      group: "listing",
      validation: (rule) => rule.required().min(20).max(220),
    }),
    defineField({
      name: "cardImage",
      title: "Card / Hero Image",
      type: "image",
      group: "listing",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "cardOverlayImage",
      title: "Card Overlay Image",
      type: "image",
      group: "listing",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "duration",
      title: "Duration Label",
      type: "string",
      group: "listing",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "certificateLabel",
      title: "Certificate Label",
      type: "string",
      group: "listing",
      initialValue: "Certificate",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "showOnHomepage",
      title: "Show On Homepage",
      type: "boolean",
      group: "listing",
      initialValue: true,
    }),
    defineField({
      name: "orderRank",
      title: "Order",
      type: "number",
      group: "listing",
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().min(10).max(140),
    }),
    defineField({
      name: "heroDescription",
      title: "Hero Description",
      type: "text",
      rows: 4,
      group: "hero",
      validation: (rule) => rule.required().min(30).max(320),
    }),
    defineField({
      name: "feeLabel",
      title: "Fee Label",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "floatingCardLabel",
      title: "Floating Card Label",
      type: "string",
      group: "hero",
      initialValue: "Outcome Focus",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "floatingCardValue",
      title: "Floating Card Value",
      type: "string",
      group: "hero",
      initialValue: "Portfolio + Confidence",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "floatingCardCopy",
      title: "Floating Card Copy",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (rule) => rule.max(180),
    }),
    defineField({
      name: "sessionDuration",
      title: "Session Duration",
      type: "string",
      group: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "classSchedule",
      title: "Class Schedule",
      type: "string",
      group: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "mode",
      title: "Mode",
      type: "string",
      group: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "overviewTitle",
      title: "Overview Title",
      type: "string",
      group: "details",
      initialValue: "What you'll learn",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "overviewParagraph",
      title: "Overview Content",
      type: "array",
      group: "details",
      of: [
        defineArrayMember({
          type: "block",
          styles: [
            { title: "Normal", value: "normal" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Number", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Underline", value: "underline" },
              { title: "Code", value: "code" },
            ],
            annotations: [
              defineArrayMember({
                name: "link",
                title: "Link",
                type: "object",
                fields: [
                  defineField({
                    name: "href",
                    title: "URL",
                    type: "url",
                    validation: (rule) => rule.required().uri({ scheme: ["http", "https", "mailto", "tel"] }),
                  }),
                  defineField({
                    name: "openInNewTab",
                    title: "Open in new tab",
                    type: "boolean",
                    initialValue: true,
                  }),
                ],
              }),
            ],
          },
        }),
        defineArrayMember({
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Alt Text",
              type: "string",
            }),
          ],
        }),
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "outcomes",
      title: "Outcomes",
      type: "array",
      group: "details",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "modules",
      title: "Modules",
      type: "array",
      group: "details",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "title",
              title: "Title",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "summary",
              title: "Summary",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required(),
            }),
          ],
          preview: {
            select: {
              title: "title",
              subtitle: "summary",
            },
          },
        }),
      ],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "featureColumns",
      title: "Feature Columns",
      type: "array",
      group: "details",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "title",
              title: "Title",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "items",
              title: "Items",
              type: "array",
              of: [defineArrayMember({ type: "string" })],
              validation: (rule) => rule.required().min(1),
            }),
          ],
          preview: {
            select: {
              title: "title",
            },
          },
        }),
      ],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "trainers",
      title: "Trainers",
      type: "array",
      group: "details",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "name",
              title: "Name",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "role",
              title: "Role",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "bio",
              title: "Bio",
              type: "text",
              rows: 4,
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "image",
              title: "Image",
              type: "image",
              options: { hotspot: true },
              fields: [
                defineField({
                  name: "alt",
                  title: "Alt Text",
                  type: "string",
                }),
              ],
            }),
          ],
          preview: {
            select: {
              title: "name",
              subtitle: "role",
              media: "image",
            },
          },
        }),
      ],
    }),
    defineField({
      name: "placementCopy",
      title: "Top Sidebar Copy",
      type: "text",
      rows: 2,
      group: "cta",
      initialValue: "CTDS certified learning path with mentor-led support and portfolio-focused practice.",
      validation: (rule) => rule.required().max(160),
    }),
    defineField({
      name: "supportCopy",
      title: "Bottom Support Copy",
      type: "text",
      rows: 2,
      group: "cta",
      initialValue: "Need help deciding if this track is right for you?",
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: "applyUrl",
      title: "Apply URL",
      type: "url",
      group: "cta",
      validation: (rule) =>
        rule.required().uri({ scheme: ["http", "https", "mailto", "tel"] }),
    }),
    defineField({
      name: "brochureUrl",
      title: "Brochure URL",
      type: "url",
      group: "cta",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "brochureFile",
      title: "Brochure File",
      type: "file",
      group: "cta",
      options: {
        accept: ".pdf,.doc,.docx",
      },
    }),
    defineField({
      name: "callNumber",
      title: "Call Number",
      type: "string",
      group: "cta",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
      validation: (rule) => rule.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: "seoImage",
      title: "SEO Image",
      type: "image",
      group: "seo",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "seoNoIndex",
      title: "No Index",
      type: "boolean",
      group: "seo",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "tag",
      media: "cardImage",
    },
  },
});
