import type { Metadata } from "next";
import AppShell from "@/components/AppShell/AppShell";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Aider Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
